apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrosentry-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrosentry-notification
  template:
    metadata:
      labels:
        app: agrosentry-notification
    spec:
      containers:
        - name: notification
          image: agrosentry-notification:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: PG_HOST
              value: "host.docker.internal"
            - name: PG_REPLICA_HOST
              value: "host.docker.internal"
            - name: PG_DB
              value: "agrosentry"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PG_PASSWORD
            - name: PG_PORT
              value: "5000"
            - name: PG_REPLICA_PORT
              value: "5001"

            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
