apiVersion: v1
kind: Service
metadata:
  name: agrosentry-notification-service
spec:
  type: ClusterIP # Internal only
  selector:
    app: agrosentry-notification
  ports:
    - port: 8002
      targetPort: 8002
