# Generated by Django 5.1.6 on 2025-03-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensor_sensortype_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
