# Generated by Django 5.1.6 on 2025-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='user',
        ),
    ]
