apiVersion: v1
kind: Service
metadata:
  name: agrosentry-web-service
spec:
  type: NodePort
  selector:
    app: agrosentry-web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
