apiVersion: v1
kind: Service
metadata:
  name: agrosentry-iot-service
spec:
  type: NodePort # NodePort to be accessible externally
  selector:
    app: agrosentry-iot
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
